### ISSUE TITLE
How to set up a Path Module

### ISSUE THREAD

**Issue by vtquan** [giraffe-fsharp/Giraffe#108]
Following the Suave Music Store tutorial with Giraffe. I got to [this section](https://theimowski.gitbooks.io/suave-music-store/content/en/path_module.html) about path module. To implement it in Giraffe, I create my Path.fs to be

```fsharp
module GiraffeMusicStore.Path

type IntPath = PrintfFormat<(int -> string),unit,string,string,int>

let home = "/"

module Store =
    let overview = "/store"
    let browse = "/store/browse"
    let details : IntPath = "/store/details/%i"
```

and my webApp function is

```fsharp
let webApp =
    choose [
        GET >=>
            choose [
                route Path.home >=> html View.home
                route Path.Store.overview >=> html View.store
                route Path.Store.browse >=> browse
                routef Path.Store.details (fun id -> negotiate (sprintf "Details %i" id))
            ]
        setStatusCode 404 >=> text "Not Found" ]
```

This give me an error on id saying ``The type 'string' is not compatible with any of the types byte,int16,int32,int64,sbyte,uint16,uint32,uint64,nativeint,unativeint, arising from the use of a printf-style format string``
From what I can see, it seems to be a problem with the typing of IntPath but I don't see where the differences arise in my implementation.

**Comment by gerardtoconnor** [comment]
the string with the format needs to in a StrintFormat function to parse results as uses compiler trick/hack to generate types, otherwise it's just a string... change IntPath to a function that accepts a StringFormat instead perhaps, then will accept string

**Comment by gerardtoconnor** [comment]
let IntPath (fmt:StringFormat<string->int,int>) = ...

**Comment by gerardtoconnor** [comment]
might work way you want it if Mark as [<literal>] but can't test atm

**Comment by vtquan** [comment]
I am getting ''StringFormat is not defined'' message

The error message also suggest replacing StringFormat with printfFormat but that gives "expects 5 type argument(s) but is given 2.

**Comment by gerardtoconnor** [comment]
open open FSharp.Core.Printf

not sure why it wants printfFormat, either it's infering from your IntParse or more likely, it's decomposed underlying rep of StringFormat... so should work if include namespace

**Comment by JonCanning** [comment]
`type IntPath = FSharp.Core.Printf.StringFormat<int -> int, int>`

**Comment by nojaf** [comment]
@vtquan sounds like an interesting sample you are building, would you consider a PR once you are done?

**Comment by gerardtoconnor** [comment]
> type IntPath = FSharp.Core.Printf.StringFormat<int -> int, int>
😆 sorry just home and looked over, @JonCanning completly right

To save prototyping all types though, it might be worth creating a local `fmt` function inside your paths module to map automatically wrap types ... what I was trying to get at ... been a long day

```fsharp
let inline fmt (sf:FSharp.Core.Printf.StringFormat<_,_>)  = sf
let path1 = fmt "testing%s"
```

**Comment by vtquan** [comment]
Thank you @JonCanning, that did the trick. Not sure why there is a difference though. Both Suave and Giraffe expect some string format and they both resolve an int to create a string to then pass it back to the client so why are the type different?

@nojaf sure, I'll send a PR once I recreate all the steps of tutorial.

@gerardtoconnor That sound interesting.  I follow your example to get the following

```fsharp
module GiraffeMusicStore.Path
open FSharp.Core

let inline fmt (sf:Printf.StringFormat<_,_>) = sf

let home = "/"

module Store =
    let overview = "/store"
    let browse = "/store/browse"
    let details = fmt "/store/details/%i"
```

``details`` is giving me an error ``Value restriction. The value 'details' has been inferred to have generic type``

**Comment by JonCanning** [comment]
`let inline fmt sf : Printf.StringFormat<_> = sf`

**Comment by gerardtoconnor** [comment]
![image](https://user-images.githubusercontent.com/5388991/31462473-cfdf0954-aec4-11e7-9c66-fefa1ac1407c.png)
That's odd, works fine for me ... Maybe stick with explicit way if not working.

@JonCanning I don't think that works as it defaults all result outputs of routef to "string", needs to be a tuple and hence why my original one won't work either.

TBH, the generic parameters are a little hacked in routef atm and i'm hoping to fix at some stage.
with StringFormat<'a,'b>, 'b is the planned final return type such that 'a will give you a curried function signature to apply the formats and finish with 'b eg
![image](https://user-images.githubusercontent.com/5388991/31463061-abaa84f8-aec6-11e7-9069-34ecab7d421f.png)

I will propose an update soon that will have `StringFormat<'a,HttpHandler>` for routef with related parse function, instead of tuple returning `tuple -> HttpHandler`, it will have format `'a` from the string format so everything tightly coupled and we can use SRTP to remove boxing on tuples and new format would be something like: 
```fsharp
routef : (sf:StringFormat<'a , HttpHandler>) (fn: 'a)`
routef "foo/%s/%i" (fun s i next ctx -> text (s + i.ToString()) next ctx )
```
@JonCanning seeing as I'm not thinking straight tonight, does curried format above make more sense from your POV to fit StringFormat better?

**Comment by vtquan** [comment]
@gerardtoconnor Your solution work for me if I put it in the same file with the routing but not in its own separate file.

**Comment by gerardtoconnor** [comment]
Well, let's leave this issue open till we have figured out a consistent, reliable way of doing it. 

Currently, the StringFormat `TResult` type is loosely bound by what is being accepted as the first argument of parse function, you can easily change the types in the functions parse tuple and the StringFormat will bind based on those types rather than the actual StringFormat string:

![image](https://user-images.githubusercontent.com/5388991/31517744-cd8e975c-af94-11e7-8e9c-1e4a9257be55.png)

**Comment by vtquan** [comment]
However the StringFormat will work, it would be nice if can use it for routef but also for sprintf so I can do something like this

```fsharp
a [ attr "href" (sprintf Path.Store.details album.Albumid)] [
    rawText album.Title
]
```

``type IntPath = FSharp.Core.Printf.StringFormat<int -> int, int>`` work for my case in routef but not for sprintf

**Comment by dustinmoris** [comment]
Can this issue be closed?

**Comment by vtquan** [comment]
I have yet to find the perfect solution for this but I have move on to something else. I don't know if gerardtoconner is still thinking about this.

**Comment by vtquan** [comment]
Apparently there was a changes how Giraffe handles route and now the original Suave instruction ``type IntPath = PrintfFormat<(int -> string),unit,string,string,int>`` will work for Giraffe without modification. I don't know which PR is responsible for this but thank you to all who work on this change.

**Comment by gerardtoconnor** [comment]
That was me, there is a bug in StringFormat abbreviation so was needed for better type restriction, glad to hear it's working for you.

**Comment by vtquan** [comment]
I see. Thank you again @gerardtoconnor!
