### ISSUE TITLE
[Template] -enablepaket flag

### ISSUE THREAD

**Issue by nicolocodev** [giraffe-fsharp/Giraffe#130]
[I'm working](https://github.com/dustinmoris/Giraffe/compare/master...nicolocodev:template-enablepaket-flag) on the template project to add the flag `-enablepaket` 'cause paket is nice 💪

I'm using [custom operations](https://github.com/dotnet/templating/wiki/%22Runnable-Project%22-Templates#customoperationsoperationsconfiguration-required-for-each-operation) in order to use conditionals on `.fsproj`:

```xml
<!-- if(enablepaket) -->
  <Import Project="..\..\.paket\Paket.Restore.targets" />
  <!-- else -->
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Cors" Version="2.0.*" />
```
it's not working by now, always get the conditional comments on fsproj... but what do you think 👍 👎?

**Comment by forki** [comment]
Sorry to interfere but why would you need a flag for paket?

Am 04.11.2017 21:45 schrieb "Nicolás Herrera" <notifications@github.com>:

**Comment by dustinmoris** [comment]
Hi, my thoughts on this is that one project doesn't need two package managers. I think Paket is cool and if there is an easy and intuitive way to change the project to use Paket instead of NuGet then I'd be open for such a change, but making the project build with two different package managers I don't think makes sense, because at the time of a build the project doesn't care if NuGet or Paket restores the dependencies and you'd only use one package manager at a time so I don't see why to add the additional overhead of supporting two technologies when only one is ever needed?

Long answer short: Either Paket or NuGet, but not both please :)

**Comment by forki** [comment]
Usually paket users are used to run paket convert-from-nuget if maintainers
of things think nuget is a good thing...

Am 06.11.2017 04:17 schrieb "Dustin Moris Gorski" <notifications@github.com

**Comment by nojaf** [comment]
Perhaps all that is needed here is some documentation on converting to paket once you scaffolded the template. Although the [paket docs](https://fsprojects.github.io/Paket/convert-from-nuget-tutorial.html) pretty much cover it.

**Comment by forki** [comment]
Please keep in mind if you want to use giraffe together with fable then you
need paket anyway. I mean I'm biased but why not do like most other f#
things and just provide paket?

Am 06.11.2017 08:12 schrieb "Florian Verdonck" <notifications@github.com>:

**Comment by nicolocodev** [comment]
@dustinmoris no, the project won't use both package managers (?), only the template will change the `.fsproj` to use either `Paket.Restore.targets` or `PackageReference` and include the `paket.references` file (if paket is enabled). I think its a minimal change, only will touch the template and benefit the users who prefer paket :)

**Comment by dustinmoris** [comment]
I see... yeah makes sense to give users the choice for the template!

**Comment by dustinmoris** [comment]
I moved this issue to the [giraffe-template](https://github.com/giraffe-fsharp/giraffe-template) repo now.
