### ISSUE TITLE
Number of maintainers

### ISSUE THREAD

**Issue by gerardtoconnor** [giraffe-fsharp/Giraffe#152]
I think currently @dustinmoris (owner) may be the only maintainer of this project and with it picking up adoption and more PRs coming in regularly, it might be a good idea to add additional maintainers so that there is not an overwhelming burden of work on Dustin. 

I think merging of PRs on design/api changes/expansions should be left to Dustin but if additional maintainers were added, would mean that urgent bug fixes could be merged quickly and free up Dustin a bit to focus on the release milestones & design etc.

Off the top of my head, @JonCanning or @forki would be good candidates to add as emergency maintainers who can push big fixes through with the understanding not to change the API drastically on merges.

**Comment by forki** [comment]
I'm voting to promote @gerardtoconnor

**Comment by gerardtoconnor** [comment]
I can do too if @forki is already stretched, happy for anyone else to throw their hat in too if they are up to it and have the familiarity with the full library. @slang25 @TheAngryByrd

**Comment by TheAngryByrd** [comment]
I'll throw my hat in.

**Comment by dustinmoris** [comment]
Hey guys, I think this is a great suggestion. I think for Giraffe to further succeed it is almost inevitable to add more maintainers, regardless of my own time, because even if I had nothing else to do other than 24/7 Giraffe it would still be necessary to add more maintainers to a project which gains wider adoption in order to further mature, add stability and promise longevity - so I'm happy to add a couple more maintainers at this point and see how it goes!

(On a different side note, but I was even considering to sign up for the .NET foundation thing, but need to understand a bit more what it means and what it gives. Would be awesome if the [.NET foundation](https://www.dotnetfoundation.org/) could be explained a bit more in depth on one of the ASP.NET team standups @jongalloway @shanselman)

**Comment by JonCanning** [comment]
I'm happy to help. Exciting to see Giraffe gathering some momentum.

**Comment by dustinmoris** [comment]
I'm just looking through the settings and playing around with what options I have to add collaborators and if there are any settings where I can define different team roles and who can do what on which branch and stuff like this... maybe I need to create an organisation though in order to have full control - sorry if I sent some notifications to some of you as part of playing around.

Any suggestions how to best organise this going forward?

**Comment by forki** [comment]
Organisation would be great.


Am 26.11.2017 12:59 schrieb "Dustin Moris Gorski" <notifications@github.com

**Comment by gerardtoconnor** [comment]
FSharp foundation is also an option? @forki has good familiarity with how big FSharp projects setup so organisation probably best way to go. Appreciate you probably need time to familiarise yourself with setup, it's foreign to me too.

**Comment by forki** [comment]
so what's the plan?

**Comment by jongalloway** [comment]
I'd be happy to help if you'd like to apply to the .NET Foundation. FSharp Foundation would also make sense, it's really whichever you'd feel is a better fit.

The writeup of what .NET Foundation does is here: https://dotnetfoundation.org/about. There's also a video on the home page of the site if that's more your thing. Big picture is that open source software foundations exist to support projects by providing services (build servers, code signing, legal, etc.), governance (basically helping to make sure your project can stay around long-term and isn't tied to one person as a single point of failure), and adoption (helping with marketing, ability to "sell" your project better in the enterprise as a foundation supported project). I'd be happy to chat or talk to explain more. I agree it would make sense to talk more about it on a community standup some time.

I've worked closely with the FSharp Foundation leaders and there's absolutely no competition, I think either of us would say whichever seems like a better fit for your project.

**Comment by dustinmoris** [comment]
Ok so I created an org now ([giraffe-fsharp](https://github.com/giraffe-fsharp/)) and sent invites to @gerardtoconnor @TheAngryByrd and @JonCanning. I'll wait for them to accept the invite, then check what the permission situation looks like and then I'll move the project over.

@jongalloway Awesome, thanks for the info! I'll read through the docs and compare it to the fsharp foundation and then apply with one of them. If you happen to talk about the .NET foundation on a standup one day then I thought it would be interesting to hear some examples of where the foundation helped a project in some way so that people like me get perhaps a better idea of what to expect.
