### ISSUE TITLE
Q: remove async await bind from task {}? 

### ISSUE THREAD

**Issue by forki** [giraffe-fsharp/Giraffe#154]
While it's convenient that let! inside task {} works against async it still hurts type inference and error reporting. I'd vote for to remove that overload and let people explicitly use Async.StartAsTask

**Comment by gerardtoconnor** [comment]
This was a requested addition from number of users, can you confirm what examples/scenarios are causing the TI issues as the bind overload should not conflict with Task overloads or statically resolved task-like overloads but I know TI on CEs always crop up so would be good to investigate as there are options like moving the bind to an extension method that should help inference resolution

**Comment by forki** [comment]
the problem is not the conflict, but that type inference is not working properly:

![image](https://user-images.githubusercontent.com/57396/33376952-f2a14a08-d50f-11e7-961e-f492e5bc19b5.png)

where is c coming from? This leads to annoying things like the follwoing everywhere:

![image](https://user-images.githubusercontent.com/57396/33377047-549d3668-d510-11e7-9b87-fb2adb879fc7.png)


or wrong error reporting:

![image](https://user-images.githubusercontent.com/57396/33377018-36fe6d0c-d510-11e7-9236-8443934ff7e8.png)

**Comment by gerardtoconnor** [comment]
Due to the SRTP for task-like binding, we will still have TI unable to propagate up to a message signature automatically

There may be a bizarre way around this and still maintain inference if we go fully task-like in binding such that the inferred `async` object would be required to have constraints ... and we extend Async to include those constraints (it may be sealed so extension methods may not work, would be a PR to FSharp.Core).

Further to the above, we could even extend the AsyncState steps to include a `AwaitAsync` such that it would then be native continuation and not rescheduling?

Another option would be to SRTP bind the members of Async into Step also to avoid updating core ... but I think the inclusion of compatibility for task-like methods may help everyone for interop going forward?

**Comment by forki** [comment]
If you fix the signatures then things may work as well. But currently it's
really annoying, especially when you have worked with async for more than
10 years ;-)

Am 29.11.2017 15:17 schrieb "Gerard" <notifications@github.com>:

**Comment by dustinmoris** [comment]
Type inference issues should be fixed now with the latest version of TaskBuilder.fs.
