### ISSUE TITLE
How to protect from CSRF when using razorHtmlView

### ISSUE THREAD

**Issue by scorelocity** [giraffe-fsharp/Giraffe#162]
Is there a recommended way to protect again CSRF in Giraffe when using razorHtmlView? RazorHtmlView appears to support adding a CSRF token to a view using @Html.AntiForgeryToken or the asp-antiforgery="true" form tag helper.

However, I don't see built in support for something analogous to the [ValidateAntiForgeryToken] attribute available for MVC controller actions. I could try to roll my own custom HttpHandler but wanted to check if there is a better way.

**Comment by gerardtoconnor** [comment]
Currently not built in but might be good addition If you need and would be interested in helping? Only issue is we wouldn't want to add dependency in base as not all people need antiforgery.

MVC tends to pile on attributes as a way of layering logic into the pipeline similar to how we compose HttpHandlers together so in order to validate the token after the view has generated it, all we need to do it create a httpHandler to validate it.

To get working with default asp.net core service: 

- first add `Microsoft.AspNetCore.Antiforgery` in nuget to your project
- in service setup, include `.AddAntiForgery()`
- Add a handler to filter, example to get you started below
```fsharp
let antiForgeryValidate : HttpHandler =
    fun next ctx -> task {
        let af = ctx.GetService<Microsoft.AspNetCore.Antiforgery.IAntiforgery>()
        let! isValid = af.IsRequestValidAsync ctx  
        if isValid then 
            next ctx
        else
            Task.FromResult None         
    }
```

**Comment by gerardtoconnor** [comment]
What are the chances, on the same day I wrote this, someone on the Japanese f# Advent calendar wrote an article on same topic 
[https://blog.recyclebin.jp/archives/4643](https://blog.recyclebin.jp/archives/4643)

**Comment by gerardtoconnor** [comment]
@dustinmoris do we want to build this handler (and a dependency on `Antiforgery` ) into `Giraffe.Razor` by default for people using Razor? Seems a bit much to split out into its own separate nuget when 90% of its usage will be with Razor views?

**Comment by TheAngryByrd** [comment]
Is razor the only time we'd want to use this?  Would other templating engines also need their own implementation?

**Comment by gerardtoconnor** [comment]
I know someone would ask that :)

In order to use is in another templating engine you have to implement your own injection of the tokens on the rendering (while razor has helper built in) so yes back-end elements will be universal across templating engines but each templating engine needs a way to render & send tokens.

On that basis, may be better to put as its own package and see if any other templating engines deploy token rendering from Antiforgery service.

**Comment by dustinmoris** [comment]
I was just about to say the same.  It's a tough one, because I think it's really small for a separate package. I would tend to either move it to Razor and then duplicate the server code for other view engines or, add that dependency to core and have the server function there, because anti forgery is probably something which every application which has a user facing front end will need to implement, so quite common. I think I wouldn't like the idea of `Giraffe.AntiForgery` as it feels a bit too small, but if it could be coupled with other server related security stuff into something like `Giraffe.AdvancedSecurity` or `Giraffe.Security` then I'd be in favour of that option! I don't want to force us to come up with useless security functions, but if we can genuinely think of other useful things like exposing some other ASP.NET security functions for password hashing, creating secure random strings/byte arrays, or what not then it might be a good idea for such a package. What do you guys think?

**Comment by TheAngryByrd** [comment]
I actually do like the concept of `Giraffe.AntiForgery`.  My thinking is, Giraffe is a functional wrapper around `Asp.Net Core` libraries.  So this would "wrap" `Microsoft.AspNetCore.Antiforgery`

Pros:
* Keeps `Microsoft.AspNetCore.Antiforgery` out of the main Giraffe base.  Good because we're not adding more dependencies than we need to.
* Keeps the scope small.  Having a generic grab bag of `Security` functions seems like scope  creep would happen easily. 

Cons:
* Discoverability, which is kind of a problem for asp.net core in general.

**Comment by dustinmoris** [comment]
Ok fair enough... I think what you say makes sense. Shall we add it to Giraffe.Razor for now and when we want to add the same for other templating engines we can split it out into Giraffe.AntiForgery and set it as a dependency in Giraffe.Razor which would probably be a non breaking change.

**Comment by dustinmoris** [comment]
A new NuGet for `Giraffe.Razor` is being built as I type. I added a [validateAntiforgerToken](https://github.com/giraffe-fsharp/Giraffe.Razor#validateantiforgerytoken) handler to Razor for now.

**Comment by pimbrouwers** [comment]
@dustinmoris For whatever it's worth to you guys, I've got some [handlers & helpers](https://github.com/pimbrouwers/Giraffe.Antiforgery) to help with this including Giraffe View Engine helpers (https://github.com/pimbrouwers/Giraffe.Antiforgery).

Obviously very basic, but I've found it useful.
