### ISSUE TITLE
routef with %d doesn't work?

### ISSUE THREAD

**Issue by isaacabraham** [giraffe-fsharp/Giraffe#184]
I have a `routef` route that looks like `%s/%s/%d`. It never finds a matching route at runtime but compiles. If I replace the route with `%s/%s/%i`, it works fine.

**Comment by dustinmoris** [comment]
`%i` stands for integer and `%d` for `int64`, which is probably what is causing the issue. This is non standard, but because there is currently no format parameter for int64s and two format parameters for int32 (why?) I decided to use one for int64s, because I thought that this might be desired for some applications.

**Comment by gerardtoconnor** [comment]
@dustinmoris not sure what we can do but most users seems to use '%d' by default for int and as a result get these issues continually raised. 

@isaacabraham do you normally always use `%d` over '%i' for int pattern?

**Comment by dustinmoris** [comment]
Yes.. it was a 50/50 chance after all. Ideally I would want to get a format parameter for `int64`, something like `%l` (for long) and then remove either `%i` or `%d` because I don't even understand why there is two format strings for a single data type. I always thought that `%d` is confusing as it can be easily misinterpreted by someone less familiar with F# to stand for `DateTime` or `Decimal` and this was probably why I randomly used `%i` for `int` and `%d` for `int64`. :/

**Comment by isaacabraham** [comment]
@gerardtoconnor yeah, I personally always use `%d`. Not sure if that's a good indicator of what's representative of the community though :-)

You could look to ameliorate this issue by making the routing engine go pop if it ever sees a `%d` route with guidance to move over to `%i`, and / or put some `///` comment that says the same thing?

**Comment by gerardtoconnor** [comment]
yeah it's a tough one to handle. I think we need to build in a type checker at startup (once-off check) to ensure the types match up so users can get immediate feedback. I'll have a look at this.

**Comment by vtquan** [comment]
When I first got started with Giraffe, I tried to use ``%d`` because I just come from the Suave Music Store tutorial which used ``%d`` and expecting it to carry over since the rest of the syntax was so familiar. I am sure that this is the case for a lot of people. Beside a type checker, I would like to see documentation on how to match on an int64 because without it, even though I know that ``%d`` is for int64, I just assume that they are treated the same but with ``http://localhost:5000/4294967297`` matching on ``%d`` which it doesn't

**Comment by gerardtoconnor** [comment]
About to do PR now, error received at startup looks like:
```
System.Exception : Error with routef parse types: '%d' for parse type System.Int64 does not match expected type System.Int32 at tuple param:2
```

**Comment by dustinmoris** [comment]
Closing this now as @gerardtoconnor fix has been released yesterday.
