### ISSUE TITLE
Accept slashes at the end of path in route*

### ISSUE THREAD

**Issue by whitebear-gh** [giraffe-fsharp/Giraffe#201]
Hello,

In most REST frameworks it is possible to accept path with or without slash at the end, ie:

we have a route `api/customers` it should be reached when we types both 
`url/api/customers` and
`url/api/customers/`

and the same if we specify route with slash the end it should match both cases.

Is it possible to add such behavior?

**Comment by gerardtoconnor** [comment]
hi @whitebear-gh 

Everything is possible, question is, is it worth adding to api surface (and all the additional coding work) to add this feature into library by default.

This has been raised before to make it the default implicit action on all routes which was not accepted but it might be worth looking into an alternative handler option for people who need it, if demand is there.

I will wait to hear back from other users/members but I would not be opposed to adding additional handler for this case as it have come up more then once as an issue.

**Comment by dustinmoris** [comment]
Hi,

I understand that for *most* web applications they do not differentiate between a route with a trailing slash or not, however from a web servers point of view and according to the HTTP spec there IS a difference between two such routes.

This means that a web framework like Giraffe cannot treat two routes like `/hello/world` and /hello/world/` as the same, because there *might* be some web applications which will want to rightfully implement different behaviour for both routes and a general purpose web framework like Giraffe should be built in such a way that this is possible.

Also because by definition both routes are not the same it could cause weird behaviour if we would start treating it as the same. For example:

```fsharp
route  `/api/customers` >=> customersHandler
routef `/api/customers/%s` >=> specificCustomerHandler
```

In the above example, what would it mean if someone visits `/api/customers/`? Would it be the first route or the second route with an empty customer name? What would happen if someone would type `/api/customers///`? Now it's even more difficult and debateable which route should be picked up.

It is certainly difficult territory and this "exceptional" behaviour which doesn't comply with the HTTP spec should really be implemented at application level and not in the framework IMHO.


The way you could do this with Giraffe at the moment would be to register both routes:

```fsharp
route `/api/customers`  >=> customersHandler
route `/api/customers/` >=> customersHandler
```

.. or you can use `routeBind`[https://github.com/giraffe-fsharp/Giraffe#routebind] with a model and a regex which gives you more control via Regex.

For example:

```fsharp
routeBind<RouteBind> "/{foo}/{bar}/{blah}(/*)" // allow 0 or more trailing slashes
routeBind<RouteBind> "/{foo}/{bar}/{blah}(/?)" // allow 0 or 1 trailing slash
```

I can see how both options might not be sufficient yet though. Perhaps similar to `routef` which accepts a format string we could implement a `router` method which accepts a `Regex` string and where users can then implement all this behaviour easily with a single route to their own liking.

**Comment by whitebear-gh** [comment]
Thanks for great answers, with that explanation I agree that it should be left as it is.  would be nice to have an option to use regex in `router` method, but to be honest I will probably never use it to handle slashes.
