### ISSUE TITLE
Add DateTime to routef 

### ISSUE THREAD

**Issue by whitebear-gh** [giraffe-fsharp/Giraffe#202]
Hi 

It would be nice to be able to get `DateTime` / `DateTimeOffset` parameters from path using `routef`. 
Is there any reason you don't handle such case or just not implemented yet?

**Comment by gerardtoconnor** [comment]
Hi @whitebear-gh 
The main reason is due to

1. printf type inference not having a `DateTime` type, it only handles primitives
2. The format of a datetime differs greatly between client/server, for eg, if sending from javascript browser, many will send as ticks from 1970, while others will send as long UTC string etc

If a general format could be agreed, and a way to infer it in printf, then we could build it in but truthfully. its almost easier to do yourself in your own preferred format: 
```f#
routef "/api/date/%i/%i/%i" (fun (y,m,d) -> Datetime(y,m,d) ... )
```

**Comment by dustinmoris** [comment]
Agreed, there's so many ways of formatting a date/time string that it will be very difficult to get it right for everyone, when in contrast it is extremely easy for each individual application to implement it's own handler with its own specific format requirements.

You could also just use a string format for your date variable and then validate it afterwards, e.g.:

```fsharp
routef "/api/person/create/%s/%s/%s" (fun (firstName, lastName, birthDate) ->
    // Validate that birthDate came in the format of mm/dd/yyyy if your api expects US format for example, otherwise return a friendly error message saying that you couldn't parse a valid month or what not)
```

**Comment by whitebear-gh** [comment]
Wow, thanks for great, fast and detailed answers. Appreciate that :) 
Thanks for clarification - issue can be closed.
