### ISSUE TITLE
Default authorization handlers

### ISSUE THREAD

**Issue by whitebear-gh** [giraffe-fsharp/Giraffe#204]
Hi guys,

I just added simple basic authentication handler to my app so I wanted to ask if would you like to accept PR  with such handler. I know that you want to keep Giraffe as thin as possible so I wanted to ask if this is direction you would like to follow (similar handler is i.e. in Suave [link](https://github.com/SuaveIO/suave/blob/9e96504a2196429ba4be6c0362438342fc39f56a/src/Suave/Authentication.fs#L42)). 

If this is not what you want to have in app code then maybe you could think about snippets list with samples? I have spent some time on investigating how to build JWT validation based on local secrets and it might be nice to share as well. 

Let me know what you think, here is basic auth handler: 

```fsharp
    let basicAuth username password=
        fun (next: HttpFunc) (ctx:HttpContext) ->
            task {
                let authHeader = (string) ctx.Request.Headers.["Authorization"]
                if not (String.IsNullOrEmpty(authHeader)) && authHeader.StartsWith("Basic") then
                    let encodedUsernamePassword = authHeader.Substring("Basic ".Length).Trim()
                    let usernamePassword = Encoding.UTF8.GetString(Convert.FromBase64String(encodedUsernamePassword))
                    let seperatorIndex = usernamePassword.IndexOf(':')
                    let user = usernamePassword.Substring(0, seperatorIndex)
                    let pass = usernamePassword.Substring(seperatorIndex + 1)
                    if user = username && pass = password then
                        return! next ctx
                    else
                        return! (setStatusCode 401 >=> setHttpHeader "WWW-Authenticate" "Basic") next ctx
                else
                    return! (setStatusCode 401 >=> setHttpHeader "WWW-Authenticate" "Basic") next ctx
            }
```

**Comment by dustinmoris** [comment]
Hi,

First of all I'm sorry for this late reply.

Secondly thank you for creating this issue and trying to improve Giraffe! Your `basicAuth` handler looks alright in principal, but unfortunately Basic Authentication is not recommended anymore due to its potential insecurity, which is why ASP.NET Core doesn't have a BasicAuthenticationMiddleware by default anymore.

Also the preferred way in adding authentication is by creating Authentication middleware in ASP.NET Core which could validate a Basic Auth request and then set the `HttpContext.User` object if successful.

In Giraffe you can use the `requiresAuthentication` handler then to check if a user has been validated. This is approach is preferred, because it would allow to have multiple different Authentication middleware at the same time whilst only having one http handler to check if a request has been authenticated.

An example of a Basic Authentication middleware can be [found here](https://github.com/blowdart/idunno.Authentication), however it is not recommended.

With that in mind I think I'm going to close this issue if that is ok with you?

**Comment by toburger** [comment]
Is this the general best practice for every ASP.NET Core middleware?

For example imagine I want to allow CORS only for a specific subroute:

```fsharp
choose [
	route "/foo" >=> text "bar"
    route "/bar" >=> enableCors >=> text "baz"
]
```

As far as I understand you I should register the ASP.NET CORS middleware globally when setting up the infrastructure and then opt in on a specific route?
Or is there a way to dynamically register the middleware based on the route?

**Comment by dustinmoris** [comment]
@toburger Yes, so I am actually looking at improving the CORS in Giraffe. The way it is in MVC is that you register CORS middleware once in an ASP.NET Core app and then use an attribute  to decorate the controller methods which should have cors enabled.

In Giraffe I need to create a new http handler which will do the same what the attribute does in MVC.

I hope to get this done over the course of the next couple weeks. Help would be appreciated if someone has a good idea how to do it.

**Comment by toburger** [comment]
I see!
Coming from Suave it needs a bit of rethinking because basically everything was built from a WebPart (like in this [CORS](http://www.fssnip.net/mL/title/CORS-response-with-Suave) example).
Whereas in Giraffe you leverage the underlying ASP.NET Core architecture.

**Comment by dustinmoris** [comment]
Agreed... the good thing is you can still use the same model as in Suave and just build all CORS handlers from scratch yourself, but it's worth exploring the ASP.NET Core way first perhaps... because it's nice how you can configure different policies in one place and then decorate individual routes with different CORS policies. Just opening up to all domains (*) and all headers (*) is a very crude way of doing CORS IMHO. I want that Giraffe makes very tight CORS as easy as very open CORS. Also CORS policies might even be different based on configuration (which environment am I deployed, is it Dev/Staging or Prod, etc.) and the ASP.NET Core way of configuring these policies makes this very easy.

**Comment by dustinmoris** [comment]
I'm closing this now as I think there's nothing to do at this point, but feel free to re-open again if you disagree with anything I said or have a different suggestion!
