### ISSUE TITLE
VS2017 Manage User Secrets tool not working

### ISSUE THREAD

**Issue by scorelocity** [giraffe-fsharp/Giraffe#205]
Not sure if this is a Giraffe issue, but Visual Studio 2017 has a tool to assist in managing application secrets:

https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?tabs=visual-studio

When this tool is used, a UserSecretsId node is added to the PropertyGroup node in the .fsproj file. When a F# Giraffe web application is then compiled, the following error is returned:

error FS0433: A function labeled with the 'EntryPointAttribute' attribute must be the last declaration in the last file in the compilation sequence.

So this tool appears to add something to the compilation sequence after the last file - Program.fs.

Can this be made to work or is there a preferred way to manage application secrets in a Giraffe project to keep them out of source control.

**Comment by dustinmoris** [comment]
Hi, thanks for reporting. I am pretty confident that this is not a Giraffe issue, but more likely related to the Secret Manager tool. Can you maybe post your fsproj here? But the issue is most certainly not Giraffe, because Giraffe is only a single NuGet package and it sounds like your problem will persist after removing that NuGet package from your fsproj. Now the question is if you have some funny fsproj which is causing this issue or if the Secret Manager does not work with F# projects in general.

**Comment by colinbull** [comment]
I pretty sure that the secrets manager relies on codegen providers thus probably does not work at all with F#

**Comment by scorelocity** [comment]
Yes, the same problem happens with a regular F# web application without Giraffe. Thanks. 

Closing.
