### ISSUE TITLE
How to post files

### ISSUE THREAD

**Issue by Potmos** [giraffe-fsharp/Giraffe#227]
I've been looking for a way to post files using giraffe, but I dont know how. The documentation is not clear about it, it says that in the SampleApp there is an example of it but I don't see how.

**Comment by dustinmoris** [comment]
Oh yeah sorry I think that might have been removed there. I'll put it in again, but you can [find examples here](https://github.com/giraffe-fsharp/Giraffe/issues/48#issuecomment-302924969).

**Comment by dustinmoris** [comment]
I've added [File Uploads](https://github.com/giraffe-fsharp/Giraffe/blob/develop/DOCUMENTATION.md#file-uploads) to the docs now.

**Comment by Potmos** [comment]
I gues it was removed from the SampleApp because it's not working with the same code.
I get expected Async<'a> but got type 'b -> HttpFuncResult error.

Trying to fix it now, thanks for pointing the right direction.

**Comment by dustinmoris** [comment]
Yes the code in the older issue was obviously working with an older version of Giraffe. Some things have changed since then, but in the example of the file upload handler it was really just the usage of `task` vs `async` and adding the `next : HttpFunc` parameter to the function. Glad you got it working now!
