### ISSUE TITLE
setStatusCode working inconsistently

### ISSUE THREAD

**Issue by vikranthc** [giraffe-fsharp/Giraffe#234]
route "/" >=> text "hello" >=> setStatusCode 401 
expected status code is 401
Actual status code  is 200

route "/" >=> setStatusCode 401 >=> text "hello"
This works as expected, we get a status code of 401

**Comment by dustinmoris** [comment]
Hi @vikranthc,

This is indeed by design. In ASP.NET Core when a function writes to the response stream then the content is being sent to the client, at which point you can't change things like the http headers or the status code anymore.

I'll mention it in the documentation. [Response writing functions](https://github.com/giraffe-fsharp/Giraffe/blob/master/DOCUMENTATION.md#response-writing) should always be the last in the composed pipeline.

**Comment by vikranthc** [comment]
thanks @dustinmoris  @rmotyka
