### ISSUE TITLE
Complex objects in query strings?

### ISSUE THREAD

**Issue by cmeeren** [giraffe-fsharp/Giraffe#244]
I'd like to parse the query string `?page[size]=20&page[number]=2` to the type `Query` below:

```f#
type Page = {Size: int; Number: int}
type Query = {Page: Page}
```

Is this possible with Giraffe? If not, are there other ways of binding complex objects in query strings? I'd rather not have to write my own query string parser.

Please also let me know if there are better ways of solving the problem (I know I can flatten the query string, but let's keep that for last).

**Comment by dustinmoris** [comment]
This is currently not possible with Giraffe. I don't think there is a standard way of doing this, because query strings are not great for complex or multidimensional data. Of course you could always serialize your data in some other format first and then pass a serialized string in the query string, but using the standard query syntax itself to serialize complex multi dimensional data will be very difficult and will certainly involve some custom parsers.

If you need to pass a complex object via querystring I'd recommend to serialize it first and then url encode it so you can pass it as a query parameter, but I'd first advice to question why you need to pass a complex object via query string in the first place. Could you not send it in the body of the request or perhaps set it as a cookie value, etc?

**Comment by cmeeren** [comment]
> Could you not send it in the body of the request

AFAIK the HTTP spec doesn't define a request body as valid for GET requests.

In any case, I don't really need it, but our front-end developer suggested using the syntax I posted, and I just wondered if Giraffe supported this in some way. It seems the best way forward is to stick to a "flat list" of query parameters (e.g. `?pagesize=20&pagenumber=2`).

**Comment by cmeeren** [comment]
On the other hand, the [JSON API spec](http://jsonapi.org/format/#fetching-pagination) specifies that this syntax is recommended for e.g. pagination. Do you think it would be possible and desirable for Giraffe to add support for this?
