### ISSUE TITLE
TryAdd instead of Add (services in AddGiraffe)

### ISSUE THREAD

**Issue by NinoFloris** [giraffe-fsharp/Giraffe#267]
As is idiomatic for libraries to use TryAdd (allows overrides to also happen before calling AddGiraffe) I hoped it would work for Giraffe as well however the pattern is not followed here https://github.com/giraffe-fsharp/Giraffe/blob/master/src/Giraffe/Middleware.fs#L113

I could PR this, it's could also be a small up for grabs/enhancement thing, I can go either way just let me know!

**Comment by dustinmoris** [comment]
Hi, have you got an example of another .NET lib which follows a `TryAdd` pattern for registering dependencies and middleware? Just trying to understand what a `TryAdd` would do differently to the current `Add` which I have seen with most libraries so far?

Many thanks!

**Comment by NinoFloris** [comment]
All of them, just look at any aspnet lib for instance, tryadd will only add if no service was registered before it, allowing users to set their own defaults and don't have libraries mess with those.

**Comment by dustinmoris** [comment]
Is this what you would be looking for?

```fsharp
member this.TryAddGiraffe() =
        this.TryAddSingleton<IJsonSerializer>(NewtonsoftJsonSerializer(NewtonsoftJsonSerializer.DefaultSettings))
        this.TryAddSingleton<IXmlSerializer>(DefaultXmlSerializer(DefaultXmlSerializer.DefaultSettings))
        this.TryAddSingleton<INegotiationConfig, DefaultNegotiationConfig>()
```

**Comment by NinoFloris** [comment]
It should replace the adds that are currently inside AddGiraffe. It's not supposed to be more API surface :)

**Comment by dustinmoris** [comment]
Hmm.. so just trying to understand the implications of this. The `.Add(..)` method will always set (and override) any previously configured dependencies (of the same abstract type). The `.TryAdd(..)` method will only set the dependencies if they are still null. Personally I can see the use case for both, or do you mean that the `TryAdd` would be a replacement for `Add`?

When I check what other .NET Core libraries do then I don't see the `.TryAdd` at all to be honest (which is why I have not really known about it): [AddMvc](https://github.com/aspnet/Mvc/blob/master/src/Microsoft.AspNetCore.Mvc/MvcServiceCollectionExtensions.cs#L27), [AddSwaggerGen](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.SwaggerGen/Application/SwaggerGenServiceCollectionExtensions.cs#L11), [AddIdentityServer](https://github.com/IdentityServer/IdentityServer4/blob/dev/src/Configuration/DependencyInjection/IdentityServerServiceCollectionExtensions.cs#L34).

From your suggestion to replace the current Adds I feel like I am missing something?

**Comment by NinoFloris** [comment]
Yes it replaces Add and you don't see it in AddMvc because it just consists
of more extension method calls to their components that do the final
TryAddSingleton etc like calls

**Comment by dustinmoris** [comment]
Ok gotcha! You're right, just digged deeper and they indeed end up using `TryAdd`. Interesting... always learning something new.
