### ISSUE TITLE
ctx.NotModifiedResponse and extra mandatory headers

### ISSUE THREAD

**Issue by cmeeren** [giraffe-fsharp/Giraffe#275]
According to https://httpstatuses.com/304:

> The server generating a 304 response MUST generate any of the following header fields that would have been sent in a 200 OK response to the same request: Cache-Control, Content-Location, Date, ETag, Expires, and Vary.

When using `ctx.NotModifiedResponse()` as recommended in the documentation, no `Cache-Control` header is inserted (naturally, since the function has no way to know which value to use here). How can I use both `ctx.NotModifiedResponse()` and manually specify additional headers? Alternatively, what would I need to do in order to return a valid "Not Modified" response manually (without using the helper - in other words, what does the helper actually do)?

**Comment by Nhowka** [comment]
From [here](https://github.com/giraffe-fsharp/Giraffe/blob/99a258bd3fbe26f46fe64ae16e64e0b13a11cf3d/src/Giraffe/Preconditional.fs#L138-L140)

```fsharp
   member this.NotModifiedResponse() =
        this.SetStatusCode StatusCodes.Status304NotModified
        Some this
```

The helper pretty much just sets the status code.

**Comment by cmeeren** [comment]
That can't be the whole story. My testing when checking using an ETag shows it also sets the ETag for the 304 response. I suppose it will also set `Last-Modified` if that's included in the check, but I haven't tested that.

**Comment by Nhowka** [comment]
This is the `SetStatusCode` [part](https://github.com/giraffe-fsharp/Giraffe/blob/99a258bd3fbe26f46fe64ae16e64e0b13a11cf3d/src/Giraffe/Core.fs#L72-L79)

```fsharp
    member this.SetStatusCode (httpStatusCode : int) =
        this.Response.StatusCode <- httpStatusCode
```

Looks like it should do much.

**Comment by cmeeren** [comment]
Then where is it the ETag is being set in the response?

**Comment by Nhowka** [comment]
Couldn't pin, but found some results looking for `EntityTagHeaderValue`. This looks like a good candidate:
https://github.com/giraffe-fsharp/Giraffe/blob/99a258bd3fbe26f46fe64ae16e64e0b13a11cf3d/src/Giraffe/Streaming.fs#L156-L187

**Comment by cmeeren** [comment]
That function calls `NotModifiedResponse`, which is what I'm doing myself, so I don't think it's relevant in this context.

**Comment by dustinmoris** [comment]
@cmeeren You are right that the current handler doesn't set any of these headers as it wouldn't know which and what value. It's more of a helper method used from within the streaming handlers which do set these headers indeed and which is one of the most common use cases.

If you want to implement your own handler you can do the following:

```fsharp
let testHandler : HttpHandler =
    fun (next : HttpFunc) (ctx : HttpContext) ->
        task {
            ctx.SetHttpHeader "key" "value"
            return ctx.NotModifiedResponse()
        }
```

**Comment by cmeeren** [comment]
Thanks! Surely at least `ETag` is known? It must necessarily be exactly the same as in the request's `If-(None-)-Match`, since otherwise there would be a proper response. Or have I misunderstood something? (I'm a bit fuzzy on the weak vs. strong ETag thing.)

**Comment by dustinmoris** [comment]
Hi @cmeeren,

A web application would only send a `304` status code if the client had sent any of the supported `If-[...]` validation headers.

Giraffe currently exposes the `ctx.ValidatePreconditions (eTag : EntityTagHeaderValue option) (lastModified : DateTimeOffset option)` extension method which will validate all of the possible validation headers, set any required response headers (e.g. the `ETag` header) and then return a result of type `Precondition` which the calling code can use to establish which response to send back.

The `Precondition` union type has the following options:

```fsharp
type Precondition =
    | NoConditionsSpecified
    | ResourceNotModified
    | ConditionFailed
    | AllConditionsMet
```

Example:

```fsharp
let testHandler (eTag : EntityTagHeaderValue option) (lastModified : DateTimeOffset option) : HttpHandler =
    fun (next : HttpFunc) (ctx : HttpContext) ->
        task {
            // The `ValidatePreconditions` will also set the response HTTP headers
            // with an ETag or Last-Modified if available.
            match ctx.ValidatePreconditions eTag lastModified with
            | ConditionFailed     -> return ctx.PreconditionFailedResponse()
            | ResourceNotModified -> return ctx.NotModifiedResponse()

            // Either all conditions were met or no conditions specified,
            // in which case you will want to send back the full response including
            // the HTTP body
            | NoConditionsSpecified 
            | AllConditionsMet ->
                return! ctx.WriteTextAsync "Send back data..."
        }
```

The `NotModifiedResponse` is only a very stupid helper method which I created so I don't have to write the same two lines from multiple places and because it reads nicer than `SetStatusCode 304`, as it explicitly mentions in the method name what the purpose of the response is.

If you want to implement your own custom conditional endpoint then you should really make use of `ValidatePreconditions` in combination with `PreconditionFailedResponse()` and `NotModifiedResponse()` as shown above.

Hope that makes sense and that this it is helpful. I thought this level of abstraction makes it still possible to implement custom conditional endpoints but still gives users the full flexibility of customizing it even further if the `ValidatePreconditions` method cannot be used for some reason.

Let me know how you get on with this and if there's anything else that I can do!

**Comment by cmeeren** [comment]
Thanks, it makes sense now. I didn't know that `ValidatePreconditions` was modifying the response.

**Comment by dustinmoris** [comment]
@cmeeren That's a good point. I might have to think about renaming the new handler perhaps.
