### ISSUE TITLE
Unexpected end of file for build.sh (OS X)

### ISSUE THREAD

**Issue by nicohvi** [giraffe-fsharp/Giraffe#283]
Hi there.

I think there might be something wrong with the giraffe template. Using `dotnet new giraffe --UsePaket` creates the following `build.sh` file:

```sh
if [ ! -e "paket.lock" ]
then
    exec mono .paket/paket.exe install
fi
dotnet restore src/test
dotnet build src/test
```

Which produces the following error when I try to run it:
```
./build.sh: line 8: syntax error: unexpected end of file
```

I'm very new to the dotnet eco-system on OS X, so there might be something I've overlooked :-)

```
.NET CLI Tools 2.1.3
```

**Comment by rmunn** [comment]
CRLF line endings strike again! Load `build.sh` into a decent text editor and change its line endings to be LF instead of CRLF, and it should work. (I could reproduce the "syntax error: unexpected end of file" behavior on Linux, and changing the line endings from CRLF to LF took care of the problem).

**Comment by rmunn** [comment]
This has already been reported as https://github.com/giraffe-fsharp/giraffe-template/issues/17, BTW.

**Comment by nicohvi** [comment]
Thanks @rmunn - that did the trick (used [dos2unix](http://dos2unix.sourceforge.net/) for the conversion).
