### ISSUE TITLE
Make Routing.getPath (+others?) public

### ISSUE THREAD

**Issue by stroborobo** [giraffe-fsharp/Giraffe#309]
Hey team!

I'm plugging our Fable.Elmish.Browser routing into our Giraffe routing right now (for server side rendering) and noticed that it seems to be impossible to get the "already routed" path out of Giraffe.

E.g. for `subRoute "/foo/" routeUI`, inside the routeUI HttpHandler I don't know the part that's already handled. I'd help if getPath would be accessible from the outside in case users want to insert their own routing into Giraffe and need to know the path that's left (and possibly the base, too).

**Comment by dustinmoris** [comment]
Sure, there is no particular reason to keep this private. I've simply made it private initially because I didn't want to expose too much functionality without a clear use case.

I will probably move these helper functions into a new module (maybe something like `SubRoute`) and make them public there. This will ensure that if someone opens the `Giraffe` module they will not have these routing functions available immediately and not get confused in how they link in with the normal routing handlers. If someone explicitly wants to make use of them they can then `open Giraffe.SubRoute` or something like that in order get access to `getPath` and the other helper functions.

This will be a quick change, I'll add it later tonight probably!

**Comment by stroborobo** [comment]
Nice, thanks!

**Comment by dustinmoris** [comment]
I've made the functionality public for the next upcoming release: https://github.com/giraffe-fsharp/Giraffe/blob/develop/RELEASE_NOTES.md#310

**Comment by dustinmoris** [comment]
This just has been released. The `3.1.0` NuGet package is still being validated and indexed on NuGet.org, but should hopefully be available soon.
