### ISSUE TITLE
Lower Newtonsoft requirements ?

### ISSUE THREAD

**Issue by MangelMaxime** [giraffe-fsharp/Giraffe#350]
Hello, I am taking a look to upgrade `SAFE-Bookstore` repo to use `Fable 2.2` and `Fable.Core v3`. 

While doing that I discovered that [Microsoft.NET.Sdk.Functions](https://www.nuget.org/packages/Microsoft.NET.Sdk.Functions/) pinned `Newtonsoft.Json` to `11.0.2`. So I lower the version required by `Thoth.Json.Net` to be `>=  11.0.2` so people using `Microsoft.NET.Sdk.Functions` can use the new major version of my library.

However, it seems like [Giraffe.fsproj](https://github.com/giraffe-fsharp/Giraffe/blob/master/src/Giraffe/Giraffe.fsproj#L51) is asking for version superior to `12.0.*`. So people will not be able to use the latest version of Giraffe if they also use Azure.

Please note, that I know almost nothing about Giraffe and Azure, but because I had the same situation with `Thoth.Json` I wanted to mention the situation so you can take a look at it and decide if something needs to change or no.

cc @nojaf because we worked together on the situation for Thoth.Json and perhaps you use Giraffe too.
cc @forki because perhaps have an opinion about it as one of the SAFE Bookstore repo

**Comment by dustinmoris** [comment]
I am a bit confused why Azure would dictate which Json library/version an application can use? Should I not be able to deploy any .NET Core application to Azure with the dependencies which my application needs? It seems strange that Azure would decide for every application that they must use Newtonsoft.Json 11.0.2. That sounds pretty stupid by Azure if you ask me. Looking at the [release notes from Newtonsoft.Json](https://github.com/JamesNK/Newtonsoft.Json/releases) it seems that there are quite a lot of useful bug fixes and other improvements in version 12, so I wouldn't necessarily want to lower the dependency because Azure is doing some weird messy stuff with dependencies?

**Comment by forki** [comment]
It's VERY complicated and people have seriously called this issue the "Steffen lssue" during talk on stage. I wish I would be joking.

Long story short: dotnet core does not offer binding redirects so users can't override versions. In case of azure functions runtime this means you are bound to use whatever the runtime uses. There is no way to override it. 

This is a bit different to the approach by AWS lambda which basically uses something that can be described as "bring your own runtime". In cases like this it's clear that BYOR is having an advantage. Anyway, in general (and not only because of the azure functions issue) it's good practice to keep the version restrictions on transitive dependencies as open as possible. This gives the resolver in client projects more freedom to come up with a sound resolution.

**Comment by forki** [comment]
> it seems that there are quite a lot of useful bug fixes and other improvements in version 12

Well you don't really do that if you open up the restriction. In the standard case the resolver in client projects will still use the latest Newtonsoft and all is well. The only thing you do is allowing people to use giraffe in situations where they can't upgrade the Newtonsoft for whatever fucked up reasons there might be.

**Comment by dustinmoris** [comment]
@forki Do you suggest to reference Newtonsoft.Json with something as low as possible like 9.*.* or something?

**Comment by forki** [comment]
As this is a library I actually think it should require the absolute
minimum. I'm not even sure if you need to require any lower bound of the
Newtonsoft at all. Is there anything specific that giraffe needs?

Dustin Moris Gorski <notifications@github.com> schrieb am Di., 16. Apr.
2019, 11:57:

**Comment by dustinmoris** [comment]
@forki You might be right. I could just reference the library without any version, but I should probably test if there really isn't a lower bound. My feeling is that there will be some lower bound. I'll have a look at this and can probably change that for the next version!

**Comment by dustinmoris** [comment]
Out in 4.0.0
