### ISSUE TITLE
Any reason why WriteFileStreamAsync can't set Last-Modified automatically?

### ISSUE THREAD

**Issue by cmeeren** [giraffe-fsharp/Giraffe#387]
`HttpContext.WriteFileStreamAsync` accepts, among other things, a file path and an optional last modified date. Is there any reason why it can't use `FileInfo` or similar to set `Last-Modified` itself? E.g.

```f#
let fi = System.IO.FileInfo path
let lastModified = DateTimeOffset(fi.LastWriteTimeUtc, TimeSpan.Zero)
```

**Comment by dustinmoris** [comment]
The reason is that the last modified date of a file might not always reflect the truth. It might be safer for a user to specify the last modified date, but I'm happy to be proven wrong. If I remember correctly there's an issue in Windows though for example where that date might not always be the actual last modified date.
