### ISSUE TITLE
Include symbols for ability to see the source code in IDE

### ISSUE THREAD

**Issue by costa100** [giraffe-fsharp/Giraffe#426]
Hello,

From time to time I want to be able to see how a function is implemented in Giraffe. Currently, vs2019 and rider.net cannot go to the giraffe source code when I click on Go To Definition or Go To Implementation.

I found this link: https://github.com/dotnet/sourcelink#using-source-link-in-net-projects.

I looked in the fsproj [file](https://github.com/giraffe-fsharp/Giraffe/blob/master/src/Giraffe/Giraffe.fsproj) and the two entries missing are:

```
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
```

Can you add them? I have to admit that I don't know if adding these two lines will enable VS2019 or Rider.Net to jump to source code. I am going to try it.

Thanks

**Comment by baronfel** [comment]
`<SymbolPackageFormat>snupkg</SymbolPackageFormat>` isn't necessary in this project because the PDBs are already included in the base nuget package. The important thing is that the PDBs are able to be located and that sourcelink is enabled, which are both done already. In fact, I started using source link information that's already embedded in Giraffe to power go-to-source in VSCode (see [this PR](https://github.com/fsharp/FsAutoComplete/pull/508/files#diff-6cae5a006ae2adbf1af79bcb20d352ebR140)) and ran into a compiler bug! 

So overall I believe that this repo is packaged correct to support sourcelink-powered go-to-definition, and either those editors or the F# Compiler Services need to be fixed to enable this experience for everyone.

**Comment by costa100** [comment]
Interesting - thanks!

**Comment by TheAngryByrd** [comment]
Closing since this has been answered.
