### ISSUE TITLE
Using Data Annotations for Model Validation

### ISSUE THREAD

**Issue by baio** [giraffe-fsharp/Giraffe#436]
Hi, I'm aware the Giraffe payload validation is using its own implementation.

But is there way to use standard ASP NET core validation based on DataAnnatations. I appreciate functional one it definitely provide more control and customization but much too verbose especially for simple cases
This 
```
    let validateData (data: SignUpData) =
        [| (validateNullOrEmpty "firstName" data.FirstName)        
           (validateNullOrEmpty "lastName" data.LastName)
           (validateNullOrEmpty "email" data.Email)
           (validateNullOrEmpty "password" data.Password) |]
        |> Array.choose id
```
Instead of that 
```
    [<CLIMutable>]
    type SignUpData =
        { [<Required>]
          FirstName: string
          [<Required>]
          LastName: string
          [<Required>]
          [<EmailAddress>]
          Email: string
          [<Required>]
          Password: string }
```

Feels less readable and more error prone

**Comment by dustinmoris** [comment]
There is nothing in Giraffe which looks for the DataAnnotations attributes. Not sure if someone else has implemented something in F# for it.

As you said, it is not very functional and the data annotations approach has many downsides which is why I normally advise against it:

- Validation is tightly coupled to the model. This is problematic if you have a model which requires different validation rules based on business logic.
- Validation only works in very few places (actually I don't know anything else that works with DataAnnotations except MVC). This is problematic again, because it means that your validation, which is a critical part of your domain logic, is not part of your domain, but is being pushed up to your application level. This kind of sucks. You couldn't use the same domain for a CLI tool which has the same functionality as MVC endpoints, because all these functions don't have a working validation anymore.
- Complex validation rules become very quickly ugly and cumbersome to manage as data annotations.
- Very complex validation rules will require additional functions, which mean that in the end you end up with the validation being split across two places, implemented via two complete different patterns

All these reasons are a huge code smell to me and why I consider validation via data annotations an anti pattern.

I know you didn't ask for my opinion, but this is the reason why I will not support such a feature in Giraffe, as I don't want to encourage programmers to use it :)

**Comment by baio** [comment]
@dustinmoris  I agree on almost  all of your points , but there is one catch I'm telling about option to validate model in the standard ASP way (not to change default model validation) for simple models this more than enough and it is more succinct and readable (IMHO). Actually this is could be extrapolated to why node ecosystem is so widespread because you  always have option to choose how to do things, and often time .net is feels little opinionated how you suppose to do stuff

**Comment by Daniel-Svensson** [comment]
To someone new to F# and giraffe this proposal sounds interesting.
I am just researching F# and the feasibility to starting use it for some projects.

Since I might use it in a environment mixed with C# classes where data annotations are quite common it would be nice to have a an easy opt in or official "workaround" code to use to get up and running a bit faster.

I've have a draft for how one might validate validation attributes, and handle the `IValidatableObject` using the built-in validator @baio but it only handle a single object and not object graphs. 
Also it has some overhead so for high usage scenarios it makes sense to only call it for object which have validation attributes or implements `IValidatableObject`

If it is of help to you and you modify it to work with giraffe you might want to post your method in this issue in case anybody else search for it.

```fsharp
    open System.ComponentModel.DataAnnotations;
    open System.Collections.Generic;

    let validateDataAnnotations (object:obj) =
        let ctx = new ValidationContext(object)
        let errors = new List<ValidationResult>()
        if Validator.TryValidateObject(object, ctx, errors, true) then None
        else Some errors
```

**Comment by baio** [comment]
@Daniel-Svensson thanks ! Exactly what I needed basic attribute base validation for the simple dto objects
