### ISSUE TITLE
how to create an async task that runs after return from handler

### ISSUE THREAD

**Issue by lanyusan** [giraffe-fsharp/Giraffe#459]
I am using Giraffe on a project and everything works great.

Now I have a use case where a REST request would trigger a long processing task that should run outside handler task.

I have tried to use 
```
task {
  // do something
}
```
within handler before `return`.
This task still blocks.

Is there a way to create a task that doesn't block handler and continues to run after handler returns, without resolving to more primitive multi threading mechanism?

Thanks in advance.

**Comment by dustinmoris** [comment]
Long running background tasks should ideally be handled by a separate host/worker because an ASP.NET Core application can not guarantee that it won't get shut at any random point in time, which would mean that you'd lose all the background work and not know at which stage it got cancelled, leaving things in funny incomplete states. For example, if your handler needs to run a long running background task, then normally it should write to some form of queue the work it needs to do, and then have a separate queue worker subscribe to that queue and process the messages to carry out the long running background tasks independently. This has several benefits. For one your ASP.NET Core application doesn't lose any work even when it crashes or gets restarted at some point, also threads are not being blocked by long running tasks and making your web application unresponsive and you can individually scale and monitor the background worker.

However, having said all of that, if you really want to start a long running background task from within an ASP.NET Core/Giraffe handler then simply don't await your function which returns a task. Don't execute it with a `do!` or `let!` binding. Simply invoke the function with `Task.Run(yourAsyncFunc())` and `|> ignore` the returning task:

```fsharp
yourAsyncFunc()
|> Task.Run
|> ignore
```

**Comment by lanyusan** [comment]
Thanks for the reply. Here I used the wrong term for my use case. It is NOT a very long background task but a relatively long task that outlives handler but not too long that has the risk you described.
