### ISSUE TITLE
Build fails with XML issues

### ISSUE THREAD

**Issue by charlesroddie** [giraffe-fsharp/Giraffe#478]
- Clone Giraffe
- Build solution
- Build fails with `1>C:\Users\charl\Source\Repos\Giraffe\src\Giraffe\ComputationExpressions.fs(1,1): error FS3390: This XML comment is invalid: 'Name cannot begin with the ''' character, hexadecimal value 0x27. Line 5, position 55.'`

**Comment by baronfel** [comment]
This is because there's no global.json checked in to source control and you're building with an SDK that enabled xml comment checking by default. It should be a simple fix, or this repository could check in an older global.json to ensure contributors are on a consistent footing.

**Comment by charlesroddie** [comment]
Failing xml checks which are genuine xml errors:
- unknown parameter
- <summary> without closing </summary>
- Unescaped anglebrackets which may need the ugly escaping of `&lt;` and `&gt;`

The xml comment checker also doesn't like incomplete `<param >` lists. C# seems OK with incomplete lists so the checker may be overzealous here.

**Comment by dustinmoris** [comment]
Thanks for reporting this issue. I encountered it myself. I think the latest SDKs have enabled the XML comment checking which previous SDKs didn't do so there were quite a few errors which went unnoticed for a while.

I've fixed them all now (as you can [see in the latest green build](https://github.com/giraffe-fsharp/Giraffe/actions/runs/816053182)).

Just an interesting side note, many errors were due to comments which included other XML tags like this:

```
/// <summary>This creates an Option<'T> bla foo bar...</summary>
```

The `<`, `>` and `'` were invalid by the checker and reading [the documentation on this](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/) I replaced it with the `{T}` notion:

```
/// <summary>This creates an Option{T} bla foo bar...</summary>
```
