### ISSUE TITLE
Improve how we can work with dynamic routes to avoid mistakes in `choose`

### ISSUE THREAD

**Issue by rahicks26** [giraffe-fsharp/Giraffe#495]
It is currently possible to incorrectly use `>=>` in a choose statement when working with `routef` for example:

```
  subRoute "/stuffs" mustBeLoggedIn >=>
      (choose [
          GET >=> routef "/%O/actions" (text "foo")
          POST >=> mustBeAdmin >=> routef "/%s/cancelliations" Routes.cancelAction
          POST >=> routef "/%O/completions" Routes.completeAction
          GET >=> tryBindQuery<ActionQuery> (validateModel Routes.getAll)
  ])
``` 
This will apply `mustBeAdmin` to both `../completions` and `../cancelliations`. While I am not :100:  sure why this works like this it is easy enough to work around. We can do that like so:

```
  subRoute "/stuffs" mustBeLoggedIn >=>
      (choose [
          GET >=> routef "/%O/actions" (text "foo")
          POST >=> routef "/%s/cancelliations" (fun p -> mustBeAdmin >=> Routes.cancelAction p)
          POST >=> routef "/%O/completions" Routes.completeAction
          GET >=> tryBindQuery<ActionQuery> (validateModel Routes.getAll)
  ])
``` 
While this works nicely it was not intuitive at first. We could make this more natural by introducing a new helper function like so:

```
let routefWith route httpHandler httpFunc = routef route (fun p -> httpHandler >=> httpFunc p)
```
Then we could use this in a number of ways. Here are a few examples:

```
  subRoute "/stuffs" mustBeLoggedIn >=>
      (choose [
          routefWith "/%O/actions" GET (text "foo")
          routefWith "/%s/cancelliations" (POST >=> mustBeAdmin) Routes.cancelAction
          routefWith "/%O/completions"  POST Routes.completeAction
          GET >=> tryBindQuery<ActionQuery> (validateModel Routes.getAll)
  ])
``` 
Often this will not be needed and could be handled by using `subRoutef` , but in the example above the is less ideal.

**Comment by dustinmoris** [comment]
The reason why it behaves like this in your first example is because the Giraffe router is basically just a big function which runs all the logic in a railway oriented way down the pipeline. The auth function appears to be in the pipeline before your router so that is why it will essentially always get executed irrespective of which router will match later on.

Your second example is exactly how one should compose their app if they wanted an auth handler to only apply to a single route. If you want to have an auth function apply to multiple routes then use subRoutes or startsWith to structure your routes into a block protected by an auth function.

I think a new helper function like the one proposed wouldn't really help people because they still need to learn the basics of how functions are bing applied/executed first before they will know which routing function to use. I think there is a critical point where adding more little convenience routers for special cases doesn't make it that much easier but maybe even harder or more confusing for users to know which one to pick. I hope you understand my thinking but for now I think I'd rather not add that router to the mix. Sorry for the disappointment but I hope you understand my reasoning.
