### ISSUE TITLE
Assembly version numbers have reverted to default 1.0.0.0 ever since NuGet version 5.0.0-alpha-002

### ISSUE THREAD

**Issue by DalekBaldwin** [giraffe-fsharp/Giraffe#521]
I haven't noticed this causing any build issues yet, but it is tripping up some other development tools.

**Comment by 64J0** [comment]
Hi @DalekBaldwin, thanks for opening this issue. Do you know if it's still happening nowadays?

**Comment by DalekBaldwin** [comment]
Yes, it's still happening. You can inspect the metadata from here: https://nuget.info/packages/Giraffe/6.4.0

**Comment by 64J0** [comment]
I noticed that this happens for other projects from the F# community as well. For example [SQLProvider](https://nuget.info/packages/SQLProvider/1.4.0):

![image](https://github.com/user-attachments/assets/f61837ea-dd04-44ac-80f0-c13e2e6198b9)

The fix is apparently to have this [AssemblyInfo](https://github.com/fsprojects/SQLProvider/blob/master/src/Common/AssemblyInfo.fs) file defining the values. I found it on [Fable](https://github.com/fable-compiler/Fable/blob/main/src/Fable.Core/AssemblyInfo.fs) too.

**Comment by baronfel** [comment]
Yous shouldn't need a dedicated assembly info file FYI - merely setting the Version property in your project file is enough to ensure that all of the relevant versioning data is stamped into your assembly.

**Comment by nojaf** [comment]
Or use https://github.com/ionide/KeepAChangelog

**Comment by 64J0** [comment]
> Or use https://github.com/ionide/KeepAChangelog

Related https://github.com/ionide/KeepAChangelog/issues/34
